/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/users/{identifier}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Returns the {identifier}'s entire profile data. */
        get: {
            parameters: {
                query?: {
                    /** @description Specific season match for statistics (default: current season number) */
                    season?: components["parameters"]["seasonParam"];
                };
                header?: never;
                path: {
                    /** @description Identifier of the user to fetch */
                    identifier: components["parameters"]["identifierParam"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description UUID (without Dashes) */
                            uuid: string;
                            nickname: string;
                            roleType: number;
                            /** @description Elo rate of current season, If user haven't finished placement matches it will be null */
                            eloRate?: number;
                            /** @description rank of current season */
                            eloRank?: number;
                            /** @description country code with lowercased ISO 3166-1 alpha-2 format */
                            country?: string;
                            achievements: {
                                /** @description A list of achievements to be displayed ingame */
                                display: components["schemas"]["Achievement"][];
                                /** @description A list of user's every achievements that are not displayed ingame */
                                total: components["schemas"]["Achievement"][];
                            };
                            timestamp: {
                                /** @description Date of user's first connection */
                                firstOnline: components["schemas"]["Date"];
                                /** @description Date of user's last connection */
                                lastOnline: components["schemas"]["Date"];
                                /** @description Date of user's last ranked match */
                                lastRanked: components["schemas"]["Date"];
                                /** @description Date of user's next decay time */
                                nextDecay?: components["schemas"]["Date"];
                            };
                            statistics: components["schemas"]["UserStatistics"];
                            connections: {
                                [key: string]: {
                                    id: string;
                                    name: string;
                                };
                            };
                            seasonResult?: components["schemas"]["seasonResult"];
                            weeklyRaces: {
                                /** @description ID of the weekly race */
                                id: number;
                                /** @description Final time of the weekly race */
                                time: components["schemas"]["Time"];
                                /** @description Rank in the weekly race */
                                rank: number;
                            }[];
                        };
                    };
                };
                default: components["responses"]["errorResponse"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{identifier}/matches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Returns the {identifier}'s entire profile data. */
        get: {
            parameters: {
                query?: {
                    /** @description Cursor of match list, it must be match ID. get matches before than ID. */
                    before?: components["parameters"]["beforeParam"];
                    /** @description Cursor of match list, it must be match ID. get matches after than ID. */
                    after?: components["parameters"]["afterParam"];
                    /** @description Match list sort option */
                    sort?: "newest" | "oldest" | "fastest" | "slowest";
                    /** @description Number of match count each page, it must 1 to 100. (default: 20) */
                    count?: components["parameters"]["countParam"];
                    /** @description Only returns match list of the selected match type. (default: null) */
                    type?: components["parameters"]["typeParam"];
                    /** @description Specific season match for statistics (default: current season number) */
                    season?: components["parameters"]["seasonParam"];
                    /** @description Whether exclude decayed matches (default: false) */
                    excludeddecay?: boolean;
                };
                header?: never;
                path: {
                    /** @description Identifier of the user to fetch */
                    identifier: components["parameters"]["identifierParam"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MatchInfo"][];
                    };
                };
                default: components["responses"]["errorResponse"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{identifier1}/versus/{identifier2}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Returns the match stats between {identifier1} and {identifier2} for ranked/casual matches. If there's no match between both users, 400 error will returned. */
        get: {
            parameters: {
                query?: {
                    /** @description Specific season match for statistics (default: current season number) */
                    season?: components["parameters"]["seasonParam"];
                };
                header?: never;
                path: {
                    /** @description Identifier of the user to fetch */
                    identifier1: components["schemas"]["UserIdentifier"];
                    /** @description Identifier of the second user to fetch */
                    identifier2: components["schemas"]["UserIdentifier"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            players: components["schemas"]["UserProfile"][];
                            /** @description Total Elo rate changes in a match between both players */
                            changes: {
                                [key: string]: string;
                            };
                        };
                    };
                };
                default: components["responses"]["errorResponse"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{identifier1}/versus/{identifier2}/matches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Returns the recent matches between {identifier1} and {identifier2}. */
        get: {
            parameters: {
                query?: {
                    /** @description Cursor of match list, it must be match ID. get matches before than ID. */
                    before?: components["parameters"]["beforeParam"];
                    /** @description Cursor of match list, it must be match ID. get matches after than ID. */
                    after?: components["parameters"]["afterParam"];
                    /** @description Number of match count each page, it must 1 to 100. (default: 20) */
                    count?: components["parameters"]["countParam"];
                    /** @description Only returns match list of the selected match type. (default: null) */
                    type?: components["parameters"]["typeParam"];
                    /** @description Specific season match for statistics (default: current season number) */
                    season?: components["parameters"]["seasonParam"];
                };
                header?: never;
                path: {
                    /** @description Identifier of the user to fetch */
                    identifier: components["parameters"]["identifierParam"];
                    /** @description Identifier of the user to fetch */
                    identifier1: components["schemas"]["UserIdentifier"];
                    /** @description Identifier of the second user to fetch */
                    identifier2: components["schemas"]["UserIdentifier"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MatchInfo"][];
                    };
                };
                default: components["responses"]["errorResponse"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{identifier}/seasons": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Returns the {identifier}'s entire profile data. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Identifier of the user to fetch */
                    identifier: components["parameters"]["identifierParam"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description UUID (without Dashes) */
                            uuid: string;
                            nickname: string;
                            roleType: number;
                            /** @description Elo rate of current season, If user haven't finished placement matches it will be null */
                            eloRate?: number;
                            /** @description rank of current season */
                            eloRank?: number;
                            /** @description country code with lowercased ISO 3166-1 alpha-2 format */
                            country?: string;
                            seasonResult?: components["schemas"]["seasonResult"];
                        };
                    };
                };
                default: components["responses"]["errorResponse"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{identifier}/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Returns real-time match data from the Private Room the player is in. To access this data, a `Private-Key` header is required. And, the player must be host or co-host of the Private Room. */
        get: {
            parameters: {
                query?: never;
                header: {
                    /** @description It can be generated in-game via Profile -> Settings -> Generate & Copy API Private Key. */
                    privatekey: string;
                };
                path: {
                    /** @description Identifier of the user to fetch */
                    identifier: components["parameters"]["identifierParam"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description Match ID of previous match. All data will be reset when the match has ended. You can get previous match data with this. */
                            last?: number;
                            /** @description The match type */
                            type: components["schemas"]["MatchType"];
                            /** @enum {string} */
                            status: "idle" | "counting" | "generate" | "ready" | "running" | "done";
                            /** @description It will be 0 if match has not started. */
                            time: components["schemas"]["Time"];
                            /** @description List of players in the game */
                            players: components["schemas"]["UserProfile"][];
                            /** @description List of players spectating the game */
                            spectators: components["schemas"]["UserProfile"][];
                            timelines: {
                                /** @description Player uuid of timeline */
                                uuid: string;
                                /** @description Match time of timeline */
                                time: components["schemas"]["Time"];
                                /** @description Identifier of timeline */
                                type: string;
                            }[];
                            completions: {
                                /** @description Player uuid of timeline */
                                uuid: string;
                                /** @description Match time of timeline */
                                time: components["schemas"]["Time"];
                            }[];
                        };
                    };
                };
                default: components["responses"]["errorResponse"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/matches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Returns the recent matches. */
        get: {
            parameters: {
                query?: {
                    /** @description Cursor of match list, it must be match ID. get matches before than ID. */
                    before?: components["parameters"]["beforeParam"];
                    /** @description Cursor of match list, it must be match ID. get matches after than ID. */
                    after?: components["parameters"]["afterParam"];
                    /** @description Number of match count each page, it must 1 to 100. (default: 20) */
                    count?: components["parameters"]["countParam"];
                    /** @description Only returns match list of the selected match type. (default: null) */
                    type?: components["parameters"]["typeParam"];
                    /** @description Specific tag of match */
                    tag?: string;
                    /** @description Specific season match for statistics (default: current season number) */
                    season?: components["parameters"]["seasonParam"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MatchInfo"][];
                    };
                };
                default: components["responses"]["errorResponse"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/matches/{match_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Returns the detailed match info. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    match_id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MatchInfo"];
                    };
                };
                default: components["responses"]["errorResponse"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Returns the online players count and live matches with public streams. You can activate public stream by follow this steps: 1. Link Twitch account with MCSR Ranked profile. 2. Make Twitch to public on MCSR Ranked profile. 3. Set "Public Stream" option in MCSR Ranked Settings. 4. Start your streaming on Twitch. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description Concurrent players count who connected to MCSR Ranked server */
                            players: number;
                            liveMatches: {
                                /** @description Current time of the match */
                                currentTime: components["schemas"]["Time"];
                                /** @description Only players with public stream activated will be included. */
                                players: components["schemas"]["UserProfile"][];
                                data: {
                                    [key: string]: {
                                        /** @description Live stream url of player. it's null if player hasn't activated public stream. */
                                        liveUrl?: string;
                                        timeline: null | {
                                            /** @description Match time of last player split update. */
                                            time: components["schemas"]["Time"];
                                            /** @description Timeline idenfitier of last player split update. */
                                            type: string;
                                        };
                                    };
                                };
                            }[];
                        };
                    };
                };
                default: components["responses"]["errorResponse"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/leaderboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Returns Top 150 Leaderboard for Elo rates (it's not always 150 players due to same ranks) */
        get: {
            parameters: {
                query?: {
                    /** @description Specific season match for statistics (default: current season number) */
                    season?: components["parameters"]["seasonParam"];
                    /** @description Specific country code with lowercased ISO 3166-1 alpha-2 format */
                    country?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description Date of season starts. */
                            startsAt: components["schemas"]["Date"];
                            /** @description Date of season ends. */
                            endsAt: components["schemas"]["Date"];
                            users: (components["schemas"]["UserProfile"] & {
                                seasonResult: {
                                    /** @description Final Elo rate of player in target season */
                                    eloRate: number;
                                    /** @description Final Elo rank of player in target season */
                                    eloRank: number;
                                    /** @description Final phase points of player in target season */
                                    phasePoint: number;
                                };
                            })[];
                        };
                    };
                };
                default: components["responses"]["errorResponse"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/phase-leaderboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Returns Top 100 Phase Points Leaderboard for Current Season */
        get: {
            parameters: {
                query?: {
                    /** @description Specific season match for statistics (default: current season number) */
                    season?: components["parameters"]["seasonParam"];
                    /** @description Specific country code with lowercased ISO 3166-1 alpha-2 format */
                    country?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            phase: {
                                /** @description Date of season ends. If target season is not current season it will be null */
                                endsAt: components["schemas"]["Date"];
                                /** @description Current phase number of the season. If target season is not current season it will be null */
                                number: number | null;
                                /** @description The season of this phase */
                                season: number;
                            };
                            users: (components["schemas"]["UserProfile"] & {
                                seasonResult: {
                                    /** @description Final Elo rate of player in target season */
                                    eloRate: number;
                                    /** @description Final Elo rank of player in target season */
                                    eloRank: number;
                                    /** @description Final phase points of player in target season */
                                    phasePoint: number;
                                };
                                /** @description Predicted phase points of player for next phase. It will be same value with `users[].seasonResult.phasePoint` if response is an past season. */
                                predPhasePoint: number;
                            })[];
                        };
                    };
                };
                default: components["responses"]["errorResponse"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/record-leaderboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Returns Top 100 Phase Points Leaderboard for Current Season */
        get: {
            parameters: {
                query?: {
                    /** @description Specific season match for statistics (default: current season number) */
                    season?: components["parameters"]["seasonParam"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            rank: number;
                            season: number;
                            date: components["schemas"]["Date"];
                            id: number;
                            time: components["schemas"]["Time"];
                            user: components["schemas"]["UserProfile"];
                            seed: components["schemas"]["MatchSeed"];
                        }[];
                    };
                };
                default: components["responses"]["errorResponse"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/weekly-race/{id?}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Returns Weekly Race info and leaderboard */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Specific week number (as id in this endpoint). (default: current weekly race) */
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            id: number;
                            seed: {
                                overworld: string;
                                nether: string;
                                theEnd: string;
                                rng: string;
                            };
                            endsAt: components["schemas"]["Date"];
                            "/leaderboard"?: {
                                rank: number;
                                player: components["schemas"]["UserProfile"];
                                time: components["schemas"]["Time"];
                                replayExist: boolean;
                            }[];
                        };
                    };
                };
                default: components["responses"]["errorResponse"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Achievement: {
            /** @description Achievement identifier */
            id: string;
            /** @description Amount of changed elo rates */
            date: components["schemas"]["Date"];
            /** @description Additional data array */
            data: string[];
            /** @description Level of Achievement */
            level: number;
            /** @description Contains current player's progression of achievement. If achievement is not leveling one, it will be null */
            value?: number;
            /** @description Next level goal of achievement. If achievement is max level or not leveling one, it will be null */
            goal?: number;
        };
        /** @description A specific date as an epoch time (timestamp) in seconds. (NOT milliseconds!) */
        Date: number;
        /** @description Advanced parameters are only available with /matches/{match_id} endpoint. */
        MatchInfo: {
            /** @description Match identifier */
            id: string;
            /** @description Match type */
            type: components["schemas"]["MatchType"];
            /** @description Season match was played in */
            season: number;
            /**
             * @description Match completion catetgory
             * @default ANY
             */
            category: string;
            /** @description Date match was played */
            date: components["schemas"]["Date"];
            /** @description List of players in the game */
            players: components["schemas"]["UserProfile"][];
            /** @description List of players spectating the game */
            spectators: components["schemas"]["UserProfile"][];
            /** @description Seed id if it's ranked filtered seed. it's not real seed number of the seed. it will be null if it's decayed match. */
            seed?: components["schemas"]["MatchSeed"];
            /** @description Results of the match */
            result: {
                /** @description Winner's UUID, It will be null If match has draw */
                uuid?: string;
                /** @description Amount of time the match took */
                time: components["schemas"]["Time"];
            };
            /** @description Whether match has no completions */
            forfeited: boolean;
            /** @description Whether match has decayed match */
            decayed: boolean;
            /** @description Rank data about the match */
            rank?: {
                /** @description Record rank of match's season */
                season?: number;
                /** @description Record rank of all-time */
                allTime?: number;
            };
            changes: {
                /** @description UUID of player */
                uuid: string;
                /** @description Amount of change Elo rate, if match has placements it will be null */
                change?: number;
                /** @description Elo rate of player, if match has placements it will be null */
                eloRate?: number;
            }[];
            /** @description Special tag of this match. It's used by get matches with tag */
            tag?: string;
            /** @description Whether match has enabled beginner mode */
            beginner: boolean;
            vod: {
                /** @description UUID of vod owner. Only players with public stream activated will be included */
                uuid: string;
                /** @description VOD url of this match with vod owner */
                url: string;
                /** @description VOD start date. you can get a timestamp with {date} - {vod[].startsAt} */
                startsAt: components["schemas"]["Date"];
            }[];
            completions: {
                /** @description (Advanced) Player uuid of completion */
                uuid: string;
                /** @description (Advanced) Match time of completion */
                time: components["schemas"]["Time"];
            }[];
            timelines: {
                /** @description (Advanced) Player uuid of timeline */
                uuid: string;
                /** @description (Advanced) Match time of timeline */
                time: components["schemas"]["Time"];
                /** @description (Advanced) Identifier of timeline */
                type: string;
            }[];
            /** @description (Advanced) Whether match replay is exist in the server */
            replayExist: boolean;
        };
        /** @description Seed of a match */
        MatchSeed: {
            /** @description Seed id if it's ranked filtered seed. it's not real seed number of the seed. it will be null if seed is not filtered. */
            id?: string;
            /** @description Overworld structure type of the seed. it will be null if seed is not filtered. */
            overworld?: string;
            /** @description Bastion remnants type of the seed. it will be null if seed is not filtered. */
            bastion?: string;
            /** @description The zero related tower heights of in The End dimension. it will be empty array if seed is not filtered. */
            endTowers: number[];
            /** @description Noticable variations of the seed. it will be empty array if seed is not filtered. */
            variations: string[];
        };
        /** @description The type of match played */
        MatchType: number;
        /** @description Displays a specific duration in milliseconds */
        Time: number;
        UserIdentifier: string;
        UserProfile: {
            /** @description User's UUID */
            uuid: string;
            /** @description User's nickname */
            nickname: string;
            /** @description User's role type */
            roleType: number;
            /** @description User's Elo rate. If user hasn't finished placement matches, it will be null */
            eloRate?: number;
            /** @description User's Elo rank. If user hasn't finished placement matches, it will be null */
            eloRank?: number;
            /** @description User's country code in a lowercased ISO 3166-1 alpha-2 format */
            country?: string;
        };
        StatisticsPairNullable: {
            ranked: number | null;
            casual: number | null;
        };
        StatisticsPairRequired: {
            ranked: number;
            casual: number;
        };
        Statistics: {
            bestTime: components["schemas"]["StatisticsPairNullable"];
            highestWinStreak: components["schemas"]["StatisticsPairRequired"];
            currentWinStreak: components["schemas"]["StatisticsPairRequired"];
            playedMatches: components["schemas"]["StatisticsPairRequired"];
            playtime: components["schemas"]["StatisticsPairRequired"];
            completionTime: components["schemas"]["StatisticsPairRequired"];
            forfeits: components["schemas"]["StatisticsPairRequired"];
            completions: components["schemas"]["StatisticsPairRequired"];
            wins: components["schemas"]["StatisticsPairRequired"];
            loses: components["schemas"]["StatisticsPairRequired"];
        };
        UserStatistics: {
            season: components["schemas"]["Statistics"];
            total: components["schemas"]["Statistics"];
        };
        seasonResult: {
            last: {
                /** @description Last Elo rate of season */
                eloRate: number;
                /** @description Last Elo rank of season */
                eloRank?: number;
                /** @description Last phase points of season */
                phasePoint: number;
            };
            /** @description Highest Elo rate of season */
            highest: number;
            /** @description Lowest Elo rate of season */
            lowest: number;
            phases: {
                /** @description Phase number */
                phase: number;
                /** @description Elo rate at phase ended */
                eloRate: number;
                /** @description Elo rank at phase ended */
                eloRank: number;
                /** @description Phase reword point */
                point: number;
            }[];
        };
    };
    responses: {
        /** @description Generic status/data response, optionally filled out data giving more detail about the error */
        errorResponse: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": {
                    /** @description The status or error information */
                    status: string;
                    /** @description What went wrong */
                    data: string | null;
                };
            };
        };
    };
    parameters: {
        /** @description Number of match count each page, it must 1 to 100. (default: 20) */
        countParam: number;
        /** @description Cursor of match list, it must be match ID. get matches before than ID. */
        beforeParam: number;
        /** @description Cursor of match list, it must be match ID. get matches after than ID. */
        afterParam: number;
        /** @description Specific season match for statistics (default: current season number) */
        seasonParam: number;
        /** @description Identifier of the user to fetch */
        identifierParam: components["schemas"]["UserIdentifier"];
        /** @description Only returns match list of the selected match type. (default: null) */
        typeParam: components["schemas"]["MatchType"];
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
