// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_middleware from "./routes/_middleware.tsx";
import * as $font_index from "./routes/font/index.tsx";
import * as $home from "./routes/home.tsx";
import * as $leaderboard_index from "./routes/leaderboard/index.tsx";
import * as $LastUpdated from "./islands/LastUpdated.tsx";
import * as $LiveMatchesGrid from "./islands/LiveMatchesGrid.tsx";
import * as $RelativeTime from "./islands/RelativeTime.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_middleware.tsx": $_middleware,
    "./routes/font/index.tsx": $font_index,
    "./routes/home.tsx": $home,
    "./routes/leaderboard/index.tsx": $leaderboard_index,
  },
  islands: {
    "./islands/LastUpdated.tsx": $LastUpdated,
    "./islands/LiveMatchesGrid.tsx": $LiveMatchesGrid,
    "./islands/RelativeTime.tsx": $RelativeTime,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
